[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3[89]* cp310* cp311*"

[tool.cibuildwheel.macos]
archs = "x86_64 universal2"

[tool.cibuildwheel.linux]
archs = "auto aarch64"
