name: Linting

on:
  pull_request:
    paths:
      - ".github/workflows/lint.yaml"
      - "**.py"
      - "Makefile"
  push:
    paths:
      - ".github/workflows/lint.yaml"
      - "**.py"
      - "Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            **/requirements/*.txt
      - name: Install dependencies
        run: make pip-install-dev
      - name: Run checks
        run: make lint